In [7]:
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu
from sklearn.metrics import confusion_matrix

Program is used to run a neural network to recognise handwritten digits from 0-9. 

In [2]:
#X is an array containing the grayscale content of a 20x20 image.
#Y contains the number it is supposed to be.

X = np.load(r"C:\Users\Fnu Aymen\Documents\Machine Learning Data\multiclassnn\X.npy")
y = np.load(r"C:\Users\Fnu Aymen\Documents\Machine Learning Data\multiclassnn\y.npy")

print("y shape:", y.shape)      
print("X shape:", X.shape)   

X_train, X_cvtest, y_train, y_cvtest = train_test_split(X, y, test_size=0.40, random_state=1)   #Splitting the data into training,cross-validation and test sets
X_cv, X_test, y_cv, y_test = train_test_split(X_cvtest, y_cvtest, test_size=0.50, random_state=1)

print("y_train shape:", y_train.shape)
print("y_cv shape:", y_cv.shape)
print("y_test shape:", y_test.shape)



y shape: (5000, 1)
X shape: (5000, 400)
y_train shape: (3000, 1)
y_cv shape: (1000, 1)
y_test shape: (1000, 1)


In [3]:
tf.random.set_seed(1234) # for consistent results
model = Sequential(
    [    
        ### START CODE HERE ### 
        Dense(32,activation='relu',name = "L3"),
        Dense(16,activation='relu',name = "L2"),
        Dense(10,activation='linear',name = "L1"),

        ### END CODE HERE ### 
    ], name = "my_model" 
)


model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=['accuracy']
)

history = model.fit(
    X_train,y_train,
    epochs=32
)


#Tried the model with different layers, epochs and learning rates. These are the best results. Results are good enough that regularisation is not required.


Epoch 1/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.2548 - loss: 2.0727
Epoch 2/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7590 - loss: 0.9497
Epoch 3/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8483 - loss: 0.5718
Epoch 4/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8877 - loss: 0.4349
Epoch 5/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9118 - loss: 0.3574
Epoch 6/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9167 - loss: 0.3089
Epoch 7/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9312 - loss: 0.2734
Epoch 8/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9367 - loss: 0.2464
Epoch 9/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9420 - loss: 0.2231
Epoch 10/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9472 - loss: 0.2037
Epoch 11/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9498 - loss: 0.1858
Epoch 12/32
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9528 - lo

In [ ]:
print("Train Accuracy:",model.evaluate(X_train,y_train)[1])
print("CV Accuracy:",model.evaluate(X_cv,y_cv)[1])
print("Test Accuracy:",model.evaluate(X_test,y_test)[1])

# Get the majority baseline accuracy on the test set
# y_test may be a column vector or 2D, ensure it's 1D for bincount
y_test_flat = y_test if y_test.ndim == 1 else y_test.ravel()
counts = np.bincount(y_test_flat)
baseline_acc = counts.max() / counts.sum()
print("Majority baseline:", baseline_acc)



# Get model predictions for the test set
y_pred_logits = model.predict(X_test)
y_pred = np.argmax(y_pred_logits, axis=1)

# Compute the confusion matrix
cm = confusion_matrix(y_test_flat, y_pred)
print("Confusion Matrix:\n", cm)




94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9969 - loss: 0.0313
Train Accuracy: 0.9959999918937683
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9213 - loss: 0.3012
CV Accuracy: 0.921999990940094
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9129 - loss: 0.3853
Test Accuracy: 0.925000011920929
Majority baseline: 0.119
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
Confusion Matrix:
 [[ 85   0   0   0   0   2   1   1   0   0]
 [  0 118   0   0   0   0   0   0   1   0]
 [  1   0  87   1   2   0   1   3   1   0]
 [  1   2   1  96   0   3   0   2   0   0]
 [  0   0   1   0 101   1   1   0   1   0]
 [  0   2   0   2   0  85   3   0   1   0]
 [  1   0   0   0   0   2  91   0   1   0]
 [  1   4   1   0   1   0   0  96   0   4]
 [  0   3   0   1   2   3   0   0  75   1]
 [  0   0   1   1   6   1   0   5   1  91]]
